#!/bin/sh

CPATH=$HOME/.config/vpn
CONFIG=lab

if [ "$1" ]; then
  if [ "$1" = "--list" ]; then
    basename -a ${CPATH}/*
    exit
  else
    CONFIG=$1
  fi
fi

FILE=$(echo ${CPATH}/*${CONFIG}*| head -n1)

echo "Connecting to $(basename ${FILE}) ..."
sudo openvpn ${FILE}
